# Generated by Django 5.0.4 on 2024-05-29 14:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='Description',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='discount_price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='product_information',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='product_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
