# Generated by Django 5.0.4 on 2024-05-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sub_category_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_Category',
        ),
    ]
