# Generated by Django 5.0.4 on 2024-05-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_sub_category'),
    ]

    operations = [
    ]
