# Generated by Django 5.0.4 on 2024-05-29 15:08

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240529_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='media/sub_category_img')),
                ('product_name', models.CharField(default=None, max_length=100)),
                ('price', models.IntegerField(default=None)),
                ('discount_price', models.IntegerField(default=None)),
                ('Description', models.CharField(max_length=300, null=True)),
                ('product_information', ckeditor.fields.RichTextField()),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.main_category')),
            ],
        ),
    ]
