# Generated by Django 5.0.4 on 2024-05-29 15:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_sub_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='Description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='discount_price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='product_information',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_category',
            name='product_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
